var { Resend } = require('resend');
var resend = new Resend(process.env.RESEND_API_KEY);
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');}
function money(v,s){return (s||'')+'€'+Number(v||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});}
function send(to,subject,html){return resend.emails.send({from:process.env.RESEND_FROM,to:to,subject:subject,html:html}).catch(function(err){console.error('Mail error:',err);});}
function statusPill(status){var s=String(status||'').toLowerCase(),bg='#edf3ff',fg='#1a56db',dot='#1a56db';if(s.indexOf('complete')>=0||s.indexOf('approved')>=0||s.indexOf('success')>=0){bg='#e9f7ef';fg='#18794e';dot='#21a366';}else if(s.indexOf('declin')>=0||s.indexOf('fail')>=0||s.indexOf('reject')>=0){bg='#fcebec';fg='#b42318';dot='#d92d20';}else if(s.indexOf('pending')>=0||s.indexOf('review')>=0){bg='#fff6df';fg='#9a6700';dot='#d99a00';}return '<span style="display:inline-block;padding:7px 11px;border-radius:999px;background:'+bg+';color:'+fg+';font-size:11px;font-weight:800;letter-spacing:.7px;text-transform:uppercase;"><span style="display:inline-block;width:6px;height:6px;border-radius:50%;background:'+dot+';margin:0 6px 1px 0;"></span>'+esc(status)+'</span>';}
function details(rows){return '<table role="presentation" width="100%" cellpadding="0" cellspacing="0">'+(rows||[]).map(function(r,i){return '<tr><td style="padding:13px 0;border-bottom:'+(i===rows.length-1?'0':'1px solid #e8edf4')+';font-size:13px;color:#738198;vertical-align:top;">'+esc(r[0])+'</td><td align="right" style="padding:13px 0;border-bottom:'+(i===rows.length-1?'0':'1px solid #e8edf4')+';font-size:13px;font-weight:700;color:#172033;vertical-align:top;word-break:break-word;">'+esc(r[1])+'</td></tr>';}).join('')+'</table>';}
function layout(content,pre,label){var y=new Date().getFullYear();return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>NovBank</title></head><body style="margin:0;padding:0;background:#edf2f7;font-family:Arial,Helvetica,sans-serif;color:#172033;-webkit-text-size-adjust:100%;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">'+esc(pre||'A secure notification from NovBank')+'</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#edf2f7;"><tr><td align="center" style="padding:28px 12px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#fff;border:1px solid #dce4ee;border-radius:14px;overflow:hidden;"><tr><td style="background:#14213d;padding:20px 28px;"><table width="100%" role="presentation"><tr><td><span style="display:inline-block;width:34px;height:34px;border-radius:8px;background:#1a56db;color:#fff;text-align:center;font-size:16px;line-height:34px;font-weight:900;">N</span><span style="display:inline-block;vertical-align:top;margin:0 0 0 10px;font-size:18px;line-height:22px;font-weight:900;color:#fff;">NovBank<br><small style="font-size:9px;letter-spacing:1.4px;color:#aebbd0;">SECURE BANKING</small></span></td><td align="right"><span style="font-size:10px;font-weight:800;letter-spacing:1px;color:#c9d3e2;">'+esc(label||'ACCOUNT NOTIFICATION')+'</span></td></tr></table></td></tr><tr><td style="padding:34px 32px 30px;">'+content+'</td></tr><tr><td style="padding:22px 32px;background:#f7f9fc;border-top:1px solid #e4eaf2;"><p style="margin:0 0 9px;font-size:11px;line-height:17px;color:#69778b;">For your security, NovBank will never ask for your password, transaction PIN or one-time verification code by email.</p><p style="margin:0;font-size:11px;color:#9aa5b5;">This is an automated message from NovBank. © '+y+' NovBank.</p></td></tr></table></td></tr></table></body></html>';}
function notify(user,subject,title,intro,amount,sign,rows,status,pre,label){var content='<div style="margin:0 0 22px;"><div style="margin-bottom:9px;font-size:10px;font-weight:900;letter-spacing:1.4px;color:#1a56db;text-transform:uppercase;">'+esc(label||'NOVBANK UPDATE')+'</div><h1 style="margin:0 0 9px;font-size:27px;line-height:34px;letter-spacing:-.6px;color:#14213d;font-weight:900;">'+esc(title)+'</h1><p style="margin:0;font-size:15px;line-height:24px;color:#59677a;">Hi '+esc(user.firstName)+', '+esc(intro)+'</p></div>'+(amount!=null?'<table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 18px;border:1px solid #dfe6ef;border-radius:12px;background:#f8fafc;"><tr><td style="padding:20px 21px 18px;border-left:4px solid #1a56db;"><div style="font-size:10px;font-weight:900;letter-spacing:1.2px;color:#7b8799;text-transform:uppercase;">Transaction amount</div><div style="margin-top:5px;font-size:31px;line-height:39px;font-weight:900;letter-spacing:-.9px;color:'+(sign==='+'?'#18794e':'#14213d')+';">'+esc(sign||'')+esc(money(amount))+'</div><div style="margin-top:9px;">'+statusPill(status)+'</div></td></tr></table>':'')+(rows&&rows.length?'<div style="padding:3px 20px;border:1px solid #dfe6ef;border-radius:12px;background:#f8fafc;">'+details(rows)+'</div>':'')+'<div style="margin-top:20px;padding:14px 15px;border:1px solid #e3e9f1;border-radius:9px;background:#fbfcfe;font-size:12px;line-height:19px;color:#69778b;">'+(label==='SECURITY'?'Never share your password or transaction PIN by email.': 'If you do not recognize this activity, sign in to NovBank and contact support immediately.')+'</div>'+(arguments[9]?'':'');return send(user.email,subject,layout(content,pre,label));}
function simple(user,subject,title,intro,rows,label,pre){return notify(user,subject,title,intro,null,'',rows,null,pre,label);}
function welcomeEmail(u){return simple(u,'Welcome to NovBank','Welcome to NovBank','your account has been created successfully.',[['Account Number',u.accountNumber],['Username','@'+u.username]],'WELCOME TO NOVBANK','Your NovBank account is ready');}
function kycApprovedEmail(u){return simple(u,'Your Identity Has Been Verified — NovBank','Identity verification approved','your identity has been verified successfully. You now have access to the full NovBank experience.',null,'IDENTITY VERIFIED','Your NovBank identity verification is complete');}
function kycDeclinedEmail(u,r){return simple(u,'Identity Verification Declined — NovBank','Verification needs attention','your identity verification was not approved. Review the reason below and resubmit your information.',[['Reason',r]],'ACTION REQUIRED','Your NovBank verification needs attention');}
function transferSentEmail(u,a,r){return notify(u,'Transfer sent · '+money(a,'-'),'Transfer sent','your transfer has been completed successfully.',a,'-',[['Recipient',r],['Date',new Date().toLocaleString('en-GB')],['Status','Completed']],'Completed','Transfer completed · '+money(a,'-'),'TRANSACTION UPDATE');}
function transferReceivedEmail(u,a,s){return notify(u,'Money received · '+money(a,'+'),'Money received','a payment has been credited to your account.',a,'+',[['From',s],['Date',new Date().toLocaleString('en-GB')],['Status','Completed']],'Completed','Money received · '+money(a,'+'),'TRANSACTION UPDATE');}
function wireTransferEmail(u,a,n,i,b){return notify(u,'Transfer pending · '+money(a,'-'),'International transfer submitted','your transfer request has been received and is pending processing.',a,'-',[['Recipient',n],['IBAN',i],['Bank',b],['Submitted',new Date().toLocaleString('en-GB')]],'Pending','International transfer submitted · awaiting processing','ACCOUNT ACTIVITY');}
function wireTransferSuccessEmail(u,a,n,i,b){return notify(u,'Wire Transfer Processed Successfully — NovBank','International transfer completed','your wire transfer was processed successfully.',a,'-',[['Recipient',n],['IBAN',i],['Destination Bank',b],['Date',new Date().toLocaleString('en-GB')],['Status','Completed']],'Completed','International wire transfer completed','ACCOUNT ACTIVITY');}
function depositRequestEmail(u,a){return notify(u,'Deposit pending · '+money(a),'Deposit request received','we have received your deposit request and it is awaiting verification.',a,'+',[['Submitted',new Date().toLocaleString('en-GB')],['Status','Pending verification']],'Pending','Deposit request received · awaiting verification','ACCOUNT ACTIVITY');}
function depositApprovedEmail(u,a){return notify(u,'Deposit Approved — NovBank','Deposit approved','your deposit has been approved and credited to your account.',a,'+',[['Date',new Date().toLocaleString('en-GB')],['Status','Approved']],'Approved','Deposit approved · '+money(a,'+'),'ACCOUNT ACTIVITY');}
function depositDeclinedEmail(u,a){return notify(u,'Deposit Declined — NovBank','Deposit not approved','your deposit request was not approved.',a,'-',[['Date',new Date().toLocaleString('en-GB')],['Status','Declined']],'Declined','Deposit request declined','ACCOUNT ACTIVITY');}
function loanApprovedEmail(u,a){return notify(u,'Loan Approved — NovBank','Loan approved','your loan request has been approved and the funds have been credited.',a,'+',[['Date',new Date().toLocaleString('en-GB')],['Status','Approved']],'Approved','Loan approved · '+money(a,'+'),'ACCOUNT ACTIVITY');}
function loanDeclinedEmail(u,a,r){return simple(u,'Loan Request Declined — NovBank','Loan request declined','your loan request was not approved. The details are below.',[['Requested Amount',money(a)],['Reason',r]],'LOAN DECISION','Your NovBank loan request was declined');}
function cardApprovedEmail(u,t){var type=t?t.charAt(0).toUpperCase()+t.slice(1):'NovBank';return simple(u,'Card Approved — NovBank','Your card is ready','your '+type+' card has been approved and is now active.',null,'CARD APPROVED','Your NovBank card has been approved');}
function forgotPasswordEmail(u,url){return notify(u,'Password Reset Request — NovBank','Reset your password','we received a request to reset your NovBank password. This link expires in 1 hour.',null,'',null,null,'Password reset requested','SECURITY');}
function forgotPinEmail(u,url){return notify(u,'PIN Reset Request — NovBank','Reset your transaction PIN','we received a request to reset your NovBank transaction PIN. This link expires in 1 hour.',null,'',null,null,'Transaction PIN reset requested','SECURITY');}
function adminKycNotification(n,e,a){return send(process.env.ADMIN_EMAIL,'New KYC Submission — NovBank',layout('<div style="margin-bottom:22px;"><div style="font-size:10px;font-weight:900;letter-spacing:1.4px;color:#1a56db;">ADMIN ACTION</div><h1 style="margin:9px 0;font-size:27px;color:#14213d;">New KYC submission</h1><p style="margin:0;font-size:15px;line-height:24px;color:#59677a;">A new identity verification request is pending review.</p></div><div style="padding:3px 20px;border:1px solid #dfe6ef;border-radius:12px;background:#f8fafc;">'+details([['Applicant',n],['Email',e],['Account Number',a],['Status','Pending review']])+'</div>', 'New KYC submission requires review','ADMIN NOTIFICATION'));}
function adminWithdrawalNotification(n,e,a,amt,type){return send(process.env.ADMIN_EMAIL,'New '+type+' — NovBank',layout('<div style="margin-bottom:22px;"><div style="font-size:10px;font-weight:900;letter-spacing:1.4px;color:#1a56db;">ADMIN ACTION</div><h1 style="margin:9px 0;font-size:27px;color:#14213d;">New '+esc(type)+'</h1><p style="margin:0;font-size:15px;line-height:24px;color:#59677a;">A new transaction requires processing.</p></div><div style="padding:3px 20px;border:1px solid #dfe6ef;border-radius:12px;background:#f8fafc;">'+details([['Customer',n],['Email',e],['Account Number',a],['Amount',money(amt)],['Type',type],['Status','Requires processing']])+'</div>','New transaction requires processing','ADMIN NOTIFICATION'));}
function emailVerificationCode(u,c){var content='<div style="margin-bottom:22px;"><div style="font-size:10px;font-weight:900;letter-spacing:1.4px;color:#1a56db;">SECURITY CHECK</div><h1 style="margin:9px 0;font-size:27px;color:#14213d;">Verify your email address</h1><p style="margin:0;font-size:15px;line-height:24px;color:#59677a;">Use the verification code below to confirm your NovBank email address.</p></div><table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="border:1px solid #d9e4f3;border-radius:12px;background:#f7faff;"><tr><td align="center" style="padding:24px;"><div style="font-size:10px;font-weight:900;letter-spacing:1.3px;color:#718096;text-transform:uppercase;">Verification code</div><div style="margin-top:9px;font-size:31px;font-weight:900;letter-spacing:8px;color:#1a56db;">'+esc(c)+'</div></td></tr></table><p style="margin:18px 0 0;font-size:13px;line-height:21px;color:#69778b;">This code expires in 15 minutes. Never share it with anyone.</p>';return send(u.email,'Your NovBank Verification Code',layout(content,'Your NovBank verification code is ready','EMAIL VERIFICATION'));}
function adminDepositEmail(u,a,b,n,num,swift,desc){return notify(u,'Deposit Received — NovBank','Deposit received','a deposit has been credited to your NovBank account.',a,'+',[['Sending Bank',b],['Account Name',n],['Account Number',num],['SWIFT/BIC Code',swift||'Not provided'],['Description',desc||'Not provided'],['Date',new Date().toLocaleString('en-GB')],['Status','Completed']],'Completed','Deposit received · '+money(a,'+'),'ACCOUNT ACTIVITY');}
module.exports={welcomeEmail:welcomeEmail,kycApprovedEmail:kycApprovedEmail,kycDeclinedEmail:kycDeclinedEmail,transferSentEmail:transferSentEmail,transferReceivedEmail:transferReceivedEmail,wireTransferEmail:wireTransferEmail,wireTransferSuccessEmail:wireTransferSuccessEmail,depositRequestEmail:depositRequestEmail,depositApprovedEmail:depositApprovedEmail,depositDeclinedEmail:depositDeclinedEmail,loanApprovedEmail:loanApprovedEmail,loanDeclinedEmail:loanDeclinedEmail,cardApprovedEmail:cardApprovedEmail,forgotPasswordEmail:forgotPasswordEmail,forgotPinEmail:forgotPinEmail,adminKycNotification:adminKycNotification,emailVerificationCode:emailVerificationCode,adminWithdrawalNotification:adminWithdrawalNotification,adminDepositEmail:adminDepositEmail};
